sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sherdg/docker_course -f Dockerfile.dev .

script:
  - docker run -e CI=true sherdg/docker_course npm run test