name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures we get all git history for versioning

      - name: Configure Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: |
          echo "Deploying version: ${{ github.sha }}"
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend3
          environment_name: Frontend3-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-381492158085
          region: eu-north-1
          version_label: "frontend-${{ github.sha }}"
          deployment_package: deploy.zip
          wait_for_deployment: true
          wait_for_environment_recovery: 300
